preloads:
  - /snpit_env/configs/${SNPIT_DEFAULT_CONFIG}

replaceable_preloads:
  - /home/environment/nov2025_container_config.yaml

photometry:
  sidecar:
    diaobject:
      diaobject_provenance_tag: "nov2025_test3"
      diaobject_process: "sidecar"

    sfft:
      back_size: 64
      back_filtersize: 3
      detect_threshold: 1.5
      detect_minarea: 5
      detect_maxarea: 0
      verbose_level: 2
      radius_cut_detmask: 1
      esatur_key: "esatur"

    candidate:
      threshold: 100
      threshold_column: "peak_value"

    psf:
      type: STPSF
