replaceable_preloads:
  - /home/environment/nov2025_container_config.yaml

photometry:
  sidecar:
    diaobject:
      diaobject_provenance_tag: "nov2025_test3"
      diaobject_process: "sidecar"

    paths:
      scratch_dir: /snpit_temp
      temp_dir: /snpit_temp
      dia_out_dir: /dia_out_dir

    psf:
      type: ou24PSF
